### ISSUE TITLE
Add "pre-commit ci" to contributors.md

### ISSUE THREAD

**Issue by cbloodsworth** [ufosc/UF-API-GROUP#28]
UF Open Source Club's API development group would not be where it is today without The Grand pre-commit ci. They have made countless contributions and have shed blood, sweat and tears for the sake of our auto-formatting. The fact that this **MAJOR** contributor is not in contributors.md is a travesty, and one that I hope is not left unhandled.

(lol)

**Comment by munnokd** [comment]
Can I work on this issue?

**Comment by cbloodsworth** [comment]
Go for it, I made this (mostly) as a joke but you're free to work on it 👍
