### ISSUE TITLE
No HTTPS support

### ISSUE THREAD

**Issue by TheShmill** [ufosc/UF-API-GROUP#33]
Cloning the repo and running the server only allows me to make HTTP connections, not HTTPS connections.

**Comment by PythiaUF** [comment]
Apologies for being so late - I haven't checked on this project in a while 😅.

Anyways, HTTPS is usually handled by program outside of your web server, like a reverse proxy - for example, you could use Cloudflare Tunnels to, alongside other things, use HTTPS. You can handle in through `uvicorn` however - [this little section on uvicorn's website](https://www.uvicorn.org/deployment/#running-with-https) explains the basics of HTTPS using uvicorn, which is what we usually do.

That being said, HTTPS is usually not needed while testing, so using HTTP in our dev environment is fine.
